"""Validity bundle assembly — package evidence into portable bundles."""
from __future__ import annotations
import json
import shutil
from pathlib import Path
from typing import Any
from .ledger import infer_claim_level


def write_validity_bundle(
    manifest: dict[str, Any],
    out_dir: Path | str,
) -> dict[str, Any]:
    """Assemble a validity bundle from a manifest dict."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    evidence_dir = out / "evidence"
    evidence_dir.mkdir(exist_ok=True)

    bundle_id = manifest.get("bundle_id", "unknown")
    claim = manifest.get("claim", {})
    metrics = manifest.get("metrics", {})
    provenance = manifest.get("provenance", {})
    audits = manifest.get("audits", {})
    attachments = manifest.get("attachments", [])

    # Write evidence files
    _write_json(evidence_dir / "claim.json", claim)
    _write_json(evidence_dir / "metrics.json", metrics)
    _write_json(evidence_dir / "provenance.json", provenance)
    _write_json(evidence_dir / "audits.json", audits)

    # Copy attachments
    copied = []
    base_dir = Path(manifest.get("base_dir", "."))
    for att in attachments:
        src = base_dir / att.get("source", "")
        dest = out / att.get("dest", Path(src).name)
        if src.exists():
            dest.parent.mkdir(parents=True, exist_ok=True)
            if src.is_dir():
                shutil.copytree(src, dest, dirs_exist_ok=True)
            else:
                shutil.copy2(src, dest)
            copied.append({"source": str(src), "dest": str(dest)})

    # Infer claim level
    claim_result = infer_claim_level(claim, metrics, audits)

    # Write manifest
    bundle_manifest = {
        "bundle_id": bundle_id,
        "claim_level": claim_result,
        "attachment_count": len(copied),
        "evidence_files": ["claim.json", "metrics.json", "provenance.json", "audits.json"],
    }
    _write_json(out / "bundle_manifest.json", bundle_manifest)

    # Write README
    readme = _render_readme(bundle_id, claim_result, metrics, provenance, audits, copied)
    (out / "README.md").write_text(readme, encoding="utf-8")

    return {
        "bundle_id": bundle_id,
        "claim_level": claim_result["level"],
        "claim_label": claim_result["label"],
        "attachment_count": len(copied),
        "out_dir": str(out),
    }


def _write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")


def _render_readme(
    bundle_id: str,
    claim_result: dict[str, Any],
    metrics: Any,
    provenance: Any,
    audits: Any,
    attachments: list[dict[str, Any]],
) -> str:
    lines = [
        f"# Validity Bundle: {bundle_id}",
        "",
        f"**Claim Level**: {claim_result['level']} — {claim_result['label']}",
        "",
    ]
    if claim_result.get("notes"):
        lines.append("**Evidence:**")
        for note in claim_result["notes"]:
            lines.append(f"- {note}")
        lines.append("")
    if isinstance(metrics, dict) and metrics:
        lines.append("## Metrics")
        for k, v in metrics.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")
    if attachments:
        lines.append(f"## Attachments ({len(attachments)})")
        for att in attachments:
            lines.append(f"- `{att['dest']}`")
        lines.append("")
    lines.append("---")
    lines.append("*Generated by heinrich*")
    return "\n".join(lines) + "\n"
