"""Query DB for paper numbers, write LaTeX commands.

Usage:
    .venv/bin/python scripts/paper_data.py

Generates paper/db_numbers.tex with commands like:
    \\newcommand{\\dbNLayers}{28}
    \\newcommand{\\dbNHeads}{784}
    \\newcommand{\\dbRefuseEncyclopediaDist}{328.3}
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure the project root is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.heinrich.db import SignalDB

PLACEHOLDER = "??"

# The primary model we reference in the paper
PRIMARY_MODEL = "mlx-community/Qwen2.5-7B-Instruct-4bit"

OUTPUT = Path(__file__).resolve().parent.parent / "paper" / "db_numbers.tex"


def _fmt(value, decimals: int = 1) -> str:
    """Format a number for LaTeX: integers stay integers, floats get fixed decimals."""
    if value is None:
        return PLACEHOLDER
    if isinstance(value, int):
        return f"{value:,}".replace(",", "{,}")
    if isinstance(value, float):
        if value == int(value):
            return f"{int(value):,}".replace(",", "{,}")
        return f"{value:.{decimals}f}"
    return str(value)


def _fmt_raw(value) -> str:
    """Format a number without thousands separators (for math superscripts etc)."""
    if value is None:
        return PLACEHOLDER
    if isinstance(value, float) and value == int(value):
        return str(int(value))
    return str(value)


def _cmd(name: str, value: str) -> str:
    """Build a \\newcommand line."""
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def main() -> None:
    db = SignalDB()

    # ---- Find primary model ----
    row = db._conn.execute(
        "SELECT id, n_layers, n_heads, d_model, n_vocab FROM models WHERE name = ?",
        (PRIMARY_MODEL,),
    ).fetchone()

    commands: list[str] = []
    commands.append("% Auto-generated by scripts/paper_data.py — do not edit by hand.")
    commands.append(f"% Primary model: {PRIMARY_MODEL}")
    commands.append("")

    if row is None:
        print(f"WARNING: model '{PRIMARY_MODEL}' not found in DB", file=sys.stderr)
        model_id = None
        n_layers = None
        n_heads_per_layer = None
        hidden_size = None
        vocab_size = None
    else:
        model_id = row["id"]
        n_layers = row["n_layers"]
        n_heads_per_layer = row["n_heads"]
        hidden_size = row["d_model"]
        vocab_size = row["n_vocab"]

    # ---- Model architecture ----
    commands.append("% --- Model architecture ---")
    commands.append(_cmd("dbNLayers", _fmt(n_layers, 0)))

    total_heads = (n_layers * n_heads_per_layer) if (n_layers and n_heads_per_layer) else None
    commands.append(_cmd("dbNHeads", _fmt(total_heads, 0)))
    commands.append(_cmd("dbNHeadsPerLayer", _fmt(n_heads_per_layer, 0)))

    commands.append(_cmd("dbHiddenSize", _fmt(hidden_size, 0)))
    commands.append(_cmd("dbHiddenSizeRaw", _fmt_raw(hidden_size)))
    commands.append(_cmd("dbVocabSize", _fmt(vocab_size, 0)))
    commands.append("")

    # ---- Table counts ----
    commands.append("% --- Table counts ---")
    count_tables = {
        "dbNEvaluations": "evaluations",
        "dbNSharts": "sharts",
        "dbNNeurons": "neurons",
        "dbNHeadsRows": "heads",
        "dbNCensorshipTopics": "censorship",
        "dbNDirections": "directions",
        "dbNInterpolations": "interpolations",
        "dbNExperiments": "experiments",
        "dbNLayersRows": "layers",
        "dbNProbes": "probes",
    }
    for cmd_name, table in count_tables.items():
        try:
            r = db._conn.execute(f"SELECT COUNT(*) as n FROM {table}").fetchone()
            commands.append(_cmd(cmd_name, _fmt(r["n"], 0)))
        except Exception:
            commands.append(_cmd(cmd_name, PLACEHOLDER))
    commands.append("")

    # ---- Censorship divergent topics ----
    commands.append("% --- Censorship ---")
    try:
        r = db._conn.execute(
            "SELECT COUNT(*) as total, SUM(divergent) as n_div FROM censorship"
        ).fetchone()
        commands.append(_cmd("dbNCensorshipTotal", _fmt(r["total"], 0)))
        commands.append(_cmd("dbNCensorshipDivergent", _fmt(int(r["n_div"]) if r["n_div"] else 0, 0)))
    except Exception:
        commands.append(_cmd("dbNCensorshipTotal", PLACEHOLDER))
        commands.append(_cmd("dbNCensorshipDivergent", PLACEHOLDER))
    commands.append("")

    # ---- Basin distances ----
    commands.append("% --- Basin distances (L2 at layer 27) ---")
    basin_pairs = [
        ("refuse", "encyclopedia", "dbRefuseEncyclopediaDist"),
        ("refuse", "procedure", "dbRefuseProcedureDist"),
        ("encyclopedia", "procedure", "dbEncyclopediaProcedureDist"),
    ]
    for a, b, cmd_name in basin_pairs:
        if model_id is not None:
            r = db._conn.execute(
                "SELECT distance FROM basin_distances "
                "WHERE model_id = ? AND "
                "((basin_a = ? AND basin_b = ?) OR (basin_a = ? AND basin_b = ?)) "
                "ORDER BY layer DESC LIMIT 1",
                (model_id, a, b, b, a),
            ).fetchone()
            if r is not None:
                commands.append(_cmd(cmd_name, _fmt(r["distance"])))
            else:
                commands.append(_cmd(cmd_name, PLACEHOLDER))
        else:
            commands.append(_cmd(cmd_name, PLACEHOLDER))
    commands.append("")

    # ---- Interpolation cliff point ----
    commands.append("% --- Interpolation cliff (alpha where behavior transitions) ---")
    if model_id is not None:
        # Find the alpha where behavior transitions from REFUSES to COMPLIES
        # Alpha goes 0.0 -> -1.0; early alphas REFUSE, later alphas COMPLY
        row_refuse = db._conn.execute(
            "SELECT alpha FROM interpolations "
            "WHERE model_id = ? AND behavior = 'REFUSES' "
            "ORDER BY alpha ASC LIMIT 1",
            (model_id,),
        ).fetchone()
        refuse_alpha = row_refuse["alpha"] if row_refuse else None

        row_comply = db._conn.execute(
            "SELECT alpha FROM interpolations "
            "WHERE model_id = ? AND behavior = 'COMPLIES' "
            "ORDER BY alpha DESC LIMIT 1",
            (model_id,),
        ).fetchone()
        comply_alpha = row_comply["alpha"] if row_comply else None

        if refuse_alpha is not None and comply_alpha is not None:
            cliff_alpha = round((refuse_alpha + comply_alpha) / 2.0, 2)
        else:
            cliff_alpha = None
        commands.append(_cmd("dbCliffAlpha", _fmt(cliff_alpha, 2) if cliff_alpha is not None else PLACEHOLDER))
    else:
        commands.append(_cmd("dbCliffAlpha", PLACEHOLDER))
    commands.append("")

    # ---- Direction effect sizes ----
    commands.append("% --- Direction effect sizes (primary model, best layer) ---")
    direction_names = ["safety", "chat", "code", "en_vs_zh"]
    cmd_map = {
        "safety": "dbSafetyEffectSize",
        "chat": "dbChatEffectSize",
        "code": "dbCodeEffectSize",
        "en_vs_zh": "dbLanguageEffectSize",
    }
    for dname in direction_names:
        cmd_name = cmd_map[dname]
        if model_id is not None:
            r = db._conn.execute(
                "SELECT effect_size, stability FROM directions "
                "WHERE model_id = ? AND name = ? ORDER BY stability DESC LIMIT 1",
                (model_id, dname),
            ).fetchone()
            if r is not None and r["effect_size"] is not None:
                commands.append(_cmd(cmd_name, _fmt(r["effect_size"])))
            else:
                commands.append(_cmd(cmd_name, PLACEHOLDER))
        else:
            commands.append(_cmd(cmd_name, PLACEHOLDER))
    commands.append("")

    # ---- Safety variance percentage ----
    # The paper says PC4 (safety) = 3.6% of variance.  This is from PCA, not stored
    # in the DB directions table directly.  We look for a signal or event that records it.
    commands.append("% --- Safety variance (PC4 percentage) ---")
    # Try signals table for a PCA variance signal
    pca_val = None
    try:
        r = db._conn.execute(
            "SELECT value FROM signals WHERE kind = 'pca_variance' AND target LIKE '%safety%' "
            "ORDER BY created_at DESC LIMIT 1"
        ).fetchone()
        if r is not None:
            pca_val = r["value"]
    except Exception:
        pass
    commands.append(_cmd("dbSafetyVariancePct", _fmt(pca_val) if pca_val is not None else PLACEHOLDER))
    commands.append("")

    # ---- Inert head percentage ----
    commands.append("% --- Head analysis ---")
    if model_id is not None:
        # Query across ALL model_ids for this model family (base + instruct share architecture)
        r = db._conn.execute(
            "SELECT COUNT(*) as total, "
            "SUM(CASE WHEN classification = 'inert' OR is_inert = 1 THEN 1 ELSE 0 END) as n_inert "
            "FROM heads WHERE classification IS NOT NULL",
        ).fetchone()
        total_h = r["total"]
        n_inert = r["n_inert"] or 0
        if total_h > 0:
            pct = round(100.0 * n_inert / total_h, 1)
            commands.append(_cmd("dbInertHeadCount", _fmt(n_inert, 0)))
            commands.append(_cmd("dbInertHeadPct", _fmt(pct)))
        else:
            commands.append(_cmd("dbInertHeadCount", PLACEHOLDER))
            commands.append(_cmd("dbInertHeadPct", PLACEHOLDER))

        # head_measurements count
        try:
            r2 = db._conn.execute(
                "SELECT COUNT(*) as n FROM head_measurements WHERE model_id = ?",
                (model_id,),
            ).fetchone()
            commands.append(_cmd("dbNHeadMeasurements", _fmt(r2["n"], 0)))
        except Exception:
            commands.append(_cmd("dbNHeadMeasurements", PLACEHOLDER))
    else:
        commands.append(_cmd("dbInertHeadCount", PLACEHOLDER))
        commands.append(_cmd("dbInertHeadPct", PLACEHOLDER))
        commands.append(_cmd("dbNHeadMeasurements", PLACEHOLDER))
    commands.append("")

    # ---- Write output ----
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(commands) + "\n"
    OUTPUT.write_text(text)
    print(f"Wrote {len(commands)} lines to {OUTPUT}")
    print(f"Commands defined: {sum(1 for c in commands if c.startswith(chr(92) + 'newcommand'))}")

    # Close writer thread cleanly
    from src.heinrich.db import _SENTINEL
    db._write_queue.put(_SENTINEL)
    db._writer_thread.join(timeout=2)


if __name__ == "__main__":
    main()
